stages:
  - build

image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  NAMESPACE: orangetalent/gitlab-ci

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

Ubuntu 8.1:
  stage: build
  variables:
    IMAGE_VERSION: "8.1-ubuntu"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/8.1/ubuntu-node-16/Dockerfile .
    - docker push $NAMESPACE:$IMAGE_VERSION
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"

Ubuntu 8.2-node-16:
  stage: build
  variables:
    IMAGE_VERSION: "8.2-ubuntu"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/8.2/ubuntu-node-16/Dockerfile .
    - docker push $NAMESPACE:$IMAGE_VERSION
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"

Ubuntu 8.2-node-18:
  stage: build
  variables:
    IMAGE_VERSION: "8.2-ubuntu-node-18"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/8.2/ubuntu-node-18/Dockerfile .
    - docker push $NAMESPACE:$IMAGE_VERSION
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"

Ubuntu 8.3-node-18:
  stage: build
  variables:
    IMAGE_VERSION: "8.3-ubuntu-node-18"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/8.3/ubuntu-node-18/Dockerfile .
    - docker push $NAMESPACE:$IMAGE_VERSION
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"

Ubuntu 8.3-node-20:
  stage: build
  variables:
    IMAGE_VERSION: "8.3-ubuntu-node-20"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/8.3/ubuntu-node-20/Dockerfile .
    - docker push $NAMESPACE:$IMAGE_VERSION
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"

Shopify-ruby-3-node-20:
  stage: build
  variables:
    IMAGE_VERSION: "shopify-ruby-3-node-20"
  script:
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f shopify/Dockerfile .
    - docker push $NAMESPACE:$IMAGE_VERSION
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"
