stages:
  - build

image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  NAMESPACE: orangetalent/gitlab-ci

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

Ubuntu 7.3:
  stage: build
  variables:
    IMAGE_VERSION: "7.3-ubuntu"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.3/ubuntu/Dockerfile .
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: manual

Ubuntu 7.4:
  stage: build
  variables:
    IMAGE_VERSION: "7.4-ubuntu"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.4/ubuntu/Dockerfile .
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: manual

Ubuntu 7.4 Node 14:
  stage: build
  variables:
    IMAGE_VERSION: "7.4-ubuntu-node-14"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.4/ubuntu-node-14/Dockerfile .
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: manual

Ubuntu 8.0:
  stage: build
  variables:
    IMAGE_VERSION: "8.0-ubuntu"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/8.0/ubuntu/Dockerfile .
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: manual
